name: AxRankMenu
version: '${project.version}'
main: com.artillexstudios.axrankmenu.AxRankMenu
api-version: '1.20'
folia-supported: true

depend:
  - LuckPerms

softdepend:
  - PlaceholderAPI
  - CoinsEngine
  - PlayerPoints
  - RoyaleEconomy
  - UltraEconomy
  - BeastTokens

permissions:
  axrankmenu.use:
    default: true
  axrankmenu.reload:
    default: op
  axrankmenu.addrank:
    default: op