name: AxRankMenu
version: '${project.version}'
main: com.artillexstudios.axrankmenu.AxRankMenu
api-version: '1.17'

depend:
  - LuckPerms

commands:
  axrankmenu:
    usage: /<command>
    aliases:
      - axranks
      - ranks
      - axrank
      - rankmenu
      - ranksmenu
      - rank

permissions:
  axrankmenu.reload:
    default: op