name: AxRankMenu
version: '${project.version}'
main: com.artillexstudios.axrankmenu.AxRankMenu
api-version: '1.17'

depend:
  - LuckPerms

commands:
  axrankmenu:
    usage: /<command>

permissions:
  axrankmenu.reload:
    default: op